const express = require("express");
const router = express.Router();
const FilesModel = require("../Models/File");
const multer = require("multer");
const path = require("path");
const fs = require("fs");

const uploadPath = path.join(__dirname, "../Uploads");
// ensure folder exists
if (!fs.existsSync(uploadPath)) {
  fs.mkdirSync(uploadPath);
}

// Create storage configuration
const storage = multer.diskStorage({
  destination: (req, file, cb) => {
    cb(null, uploadPath);
  },
  filename: (req, file, cb) => {
    // Rename file: current timestamp + original extension
    const uniqueSuffix = Date.now() + "-" + file.originalname;
    cb(null, uniqueSuffix);
  },
});

// Initialize upload middleware
const upload = multer({ storage: storage });

router.post("/upload", upload.array("files"), async (req, res) => {
  try {
    // Check if files were uploaded
    if (!req.files || req.files.length === 0) {
      return res.status(400).json({ message: "No files uploaded" });
    }

    const filesToSave = [];

    // Process each uploaded file
    for (let i = 0; i < req.files.length; i++) {
      const file = req.files[i];

      const fileData = {
        stored_name: file.filename, // Use the name generated by multer
        original_name: file.originalname,
        owner: req.body.owner || "faculty",
      };

      const newFile = new FilesModel(fileData);
      await newFile.save();
      filesToSave.push(newFile);
    }

    res.status(201).json({
      message: "Files uploaded successfully",
      files: filesToSave,
    });
  } catch (error) {
    console.error(error);
    res.status(500).json({
      message: "Error uploading files",
      error: error.message,
    });
  }
});

// GET all files
router.get("/", async (req, res) => {
  try {
    const result = await FilesModel.find();
    res.json(result);
  } catch (err) {
    res.status(500).json({ message: "Error fetching files", error: err });
  }
});

module.exports = router;
